import { SellerCase, SellerCaseStatus, SellerCaseStats } from "./types";

export const mockSellerCases: SellerCase[] = [
  {
    id: "sc-001",
    sellerId: "seller-001",
    sellerName: "TechStore Premium",
    sellerEmail: "contact@techstorepremium.com",
    platform: "amazon.com",
    status: SellerCaseStatus.INITIATED,
    reportDate: "2024-01-15T10:30:00Z",
    lastUpdated: "2024-01-15T10:30:00Z",
    caseNumber: "CS-2024-001",
    description:
      "Reported for selling counterfeit Apple products with fake authentication certificates",
    reportedBy: "Brand Protection Team",
    evidenceCount: 8,
    priority: "high",
    tags: ["counterfeit", "electronics", "apple"],
  },
  {
    id: "sc-002",
    sellerId: "seller-002",
    sellerName: "Fashion Forward LLC",
    sellerEmail: "support@fashionforward.com",
    platform: "ebay.com",
    status: SellerCaseStatus.EXPERT_REVIEW,
    reportDate: "2024-01-10T14:20:00Z",
    lastUpdated: "2024-01-20T09:15:00Z",
    caseNumber: "CS-2024-002",
    description:
      "Suspected of selling fake designer handbags with forged authenticity documents",
    reportedBy: "Customer Complaint",
    evidenceCount: 12,
    priority: "high",
    tags: ["counterfeit", "fashion", "luxury"],
  },
  {
    id: "sc-003",
    sellerId: "seller-003",
    sellerName: "HomeDecor Plus",
    sellerEmail: "orders@homedecorplus.net",
    platform: "etsy.com",
    status: SellerCaseStatus.MEDIATION,
    reportDate: "2024-01-05T16:45:00Z",
    lastUpdated: "2024-01-25T11:30:00Z",
    caseNumber: "CS-2024-003",
    description: "Copyright infringement on exclusive home decoration designs",
    reportedBy: "IP Rights Holder",
    evidenceCount: 15,
    priority: "medium",
    tags: ["copyright", "home-decor", "design"],
  },
  {
    id: "sc-004",
    sellerId: "seller-004",
    sellerName: "SportGear Pro",
    sellerEmail: "info@sportgearpro.com",
    platform: "amazon.com",
    status: SellerCaseStatus.COMPENSATION_RECEIVED,
    reportDate: "2023-12-20T08:15:00Z",
    lastUpdated: "2024-01-28T14:20:00Z",
    caseNumber: "CS-2024-004",
    description: "Counterfeit Nike products with fake logos and materials",
    reportedBy: "Brand Protection Team",
    compensationAmount: 15000,
    evidenceCount: 20,
    priority: "high",
    tags: ["counterfeit", "sports", "nike"],
  },
  {
    id: "sc-005",
    sellerId: "seller-005",
    sellerName: "ElectroWorld",
    sellerEmail: "sales@electroworld.biz",
    platform: "alibaba.com",
    status: SellerCaseStatus.CLOSED,
    reportDate: "2023-12-15T12:00:00Z",
    lastUpdated: "2024-01-30T10:45:00Z",
    caseNumber: "CS-2024-005",
    description: "Resolved case for selling uncertified electronic devices",
    reportedBy: "Regulatory Authority",
    compensationAmount: 8500,
    evidenceCount: 6,
    priority: "medium",
    tags: ["regulatory", "electronics", "certification"],
  },
  {
    id: "sc-006",
    sellerId: "seller-006",
    sellerName: "Luxury Watches Co",
    sellerEmail: "contact@luxurywatches.co",
    platform: "amazon.com",
    status: SellerCaseStatus.INITIATED,
    reportDate: "2024-01-28T15:30:00Z",
    lastUpdated: "2024-01-28T15:30:00Z",
    caseNumber: "CS-2024-006",
    description: "Selling replica watches as authentic luxury timepieces",
    reportedBy: "Customer Complaint",
    evidenceCount: 4,
    priority: "high",
    tags: ["counterfeit", "luxury", "watches"],
  },
  {
    id: "sc-007",
    sellerId: "seller-007",
    sellerName: "BeautyEssentials Hub",
    sellerEmail: "support@beautyessentials.hub",
    platform: "ebay.com",
    status: SellerCaseStatus.EXPERT_REVIEW,
    reportDate: "2024-01-22T11:15:00Z",
    lastUpdated: "2024-01-29T16:20:00Z",
    caseNumber: "CS-2024-007",
    description: "Counterfeit cosmetics with potentially harmful ingredients",
    reportedBy: "Health Authority",
    evidenceCount: 9,
    priority: "high",
    tags: ["counterfeit", "cosmetics", "health-risk"],
  },
];

export const mockSellerCaseStats: SellerCaseStats = {
  totalCases: 45,
  openCases: 32,
  closedCases: 13,
  inMediationCases: 8,
  compensationReceived: 125000,
};
