import { ROUTES } from "./routes";

export const AUTH_CONFIG = {
  PROTECTED_ROUTES: [ROUTES.USER_DASHBOARD, ROUTES.ADMIN_DASHBOARD],

  PUBLIC_ROUTES: [ROUTES.USER_DASHBOARD_LOGOUT, ROUTES.ADMIN_DASHBOARD_LOGOUT],

  AUTH_ROUTES: [
    ROUTES.USER_DASHBOARD_SIGN_IN,
    ROUTES.USER_DASHBOARD_SIGN_UP,
    ROUTES.ADMIN_DASHBOARD_SIGN_IN,
  ],
} as const;
